//
// Created by yan on 4/7/26.
//

#ifndef NUCLEOL476RG_BMP280_PORTEXPANDER_H
#define NUCLEOL476RG_BMP280_PORTEXPANDER_H

// Includes 

#include <stm32f1xx.h>
#include "I2C.h"

// MCP23017 registers

#define MCP23017_REGISTER_IODIRA        (0x00) // I/O DIRECTION REGISTER
#define MCP23017_REGISTER_IODIRB        (0x01) // I/O DIRECTION REGISTER
#define MCP23017_REGISTER_IPOLA         (0x02) // INPUT POLARITY REGISTER
#define MCP23017_REGISTER_IPOLB         (0x03) // INPUT POLARITY REGISTER
#define MCP23017_REGISTER_GPINTENA      (0x04) // INTERRUPT-ON-CHANGE CONTROL REGISTER
#define MCP23017_REGISTER_GPINTENB      (0x05) // INTERRUPT-ON-CHANGE CONTROL REGISTER
#define MCP23017_REGISTER_DEFVALA       (0x06) // DEFAULT COMPARE REGISTER FOR INTERRUPT-ON-CHANGE
#define MCP23017_REGISTER_DEFVALB       (0x07) // DEFAULT COMPARE REGISTER FOR INTERRUPT-ON-CHANGE
#define MCP23017_REGISTER_INTCONA       (0x08) // INTERRUPT CONTROL REGISTER
#define MCP23017_REGISTER_INTCONB       (0x09) // INTERRUPT CONTROL REGISTER
#define MCP23017_REGISTER_IOCONA        (0x0A) // CONFIGURATION REGISTER
#define MCP23017_REGISTER_IOCONB        (0x0B) // CONFIGURATION REGISTER
#define MCP23017_REGISTER_GPPUA         (0x0C) // PULL-UP RESISTOR CONFIGURATION REGISTER
#define MCP23017_REGISTER_GPPUB         (0x0D) // PULL-UP RESISTOR CONFIGURATION REGISTER
#define MCP23017_REGISTER_INTFA         (0x0E) // INTERRUPT FLAG REGISTER
#define MCP23017_REGISTER_INTFB         (0x0F) // INTERRUPT FLAG REGISTER
#define MCP23017_REGISTER_INTCAPA       (0x10) // INTERRUPT CAPTURE REGISTER
#define MCP23017_REGISTER_INTCAPB       (0x11) // INTERRUPT CAPTURE REGISTER
#define MCP23017_REGISTER_GPIOA         (0x12) // PORT REGISTER
#define MCP23017_REGISTER_GPIOB         (0x13) // PORT REGISTER
#define MCP23017_REGISTER_OLATA         (0x14) // OUTPUT LATCH REGISTER (OLAT)
#define MCP23017_REGISTER_OLATB         (0x15) // OUTPUT LATCH REGISTER (OLAT)

// Configuartion for MCP23017

#define MCP23017_SEQOP_OFF              (0x10)
#define MCP23017_IODIR_ALL_OUTPUT       (0x00)
#define MCP23017_IODIR_ALL_INPUT        (0xFF)


// Typedef MCP23017

typedef enum
{
    PORT_A,
    PORT_B
} PortDef;


// Init configuartion MCP23017
int8_t InitPortExpander(uint8_t devAdr);

// Set configuartion Port
int8_t PortExpanderSetConfig(uint8_t devAdr, PortDef port);

// Read / Write Port 
int8_t PortExpanderReadInput(uint8_t devAdr, PortDef port, uint8_t value);
int8_t PortExpanderWriteOutput(uint8_t devAdr, PortDef port, uint8_t value);


#endif //NUCLEOL476RG_BMP280_PORTEXPANDER_H
